# ---- Builder Stage ----
# Use a full Python image to build our dependencies
FROM python:3.10 as builder

# Set the working directory
WORKDIR /install

# Install sentence-transformers with a CPU-only version of PyTorch
# This is the key step to reduce the size. We specify the PyTorch version and that we don't need CUDA.
RUN pip install --no-cache-dir \
    torch==2.3.1 --index-url https://download.pytorch.org/whl/cpu \
    && pip install --no-cache-dir sentence-transformers


# Use a slim base image with Python
FROM rayproject/ray:2.37.0


# Create working directory
WORKDIR /app
COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

USER root

RUN chown -R ray /app

USER ray

COPY serve-chat-completion.py .

ENV PYTHONPATH="/app:${PYTHONPATH}"

CMD []