apiVersion: ray.io/v1
kind: RayService
metadata:
  name: llama-1p1b-on-raycluster
  namespace: default
spec:
  serveConfigV2: |
    applications:
    - name: llm
      route_prefix: /
      import_path: vllm.entrypoints.openai.api_server:app
      runtime_env:
        env_vars:
          MODEL: "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"
          TENSOR_PARALLEL_SIZE: "1"
          MAX_MODEL_LEN: "4096"
          CHAT_TEMPLATE: "/templates/tool_chat_template_tinyllama_json.jinja"
          RAY_ADDRESS: "ray://pytorch-mnist-cluster-head.default.svc.cluster.local:10001"
      deployments:
      - name: VLLMDeployment
        num_replicas: 1
        ray_actor_options:
          num_gpus: 1
        pod_spec:
          containers:
          - name: vllm-serve
            image: us-docker.pkg.dev/vertex-ai/vertex-vision-model-garden-dockers/pytorch-vllm-serve:20250312_0916_RC01
            resources:
              limits:
                cpu: "1"
                memory: "8Gi"
                nvidia.com/gpu: "1"
              requests:
                cpu: "1"
                memory: "8Gi"
                nvidia.com/gpu: "1"
---
# See: https://github.com/vllm-project/vllm/blob/main/examples/tool_chat_template_llama3.1_json.jinja
apiVersion: v1
kind: ConfigMap
metadata:
  name: llama-chat-templates
data:
  tool_chat_template_tinyllama_json.jinja: |
    {%- for message in messages %}
      {%- if message['role'] == 'system' %}
          {{- '<|im_start|>system\n' + message['content'] + '<|im_end|>\n' }}
      {%- elif message['role'] == 'user' %}
          {{- '<|im_start|>user\n' + message['content'] + '<|im_end|>\n' }}
      {%- elif message['role'] == 'assistant' %}
          {{- '<|im_start|>assistant\n' + message['content'] + '<|im_end|>\n' }}
      {%- endif %}
    {%- endfor %}
    {{- '<|im_start|>assistant\n' }}