apiVersion: v1
kind: Secret
metadata:
  name: hf-secret
  namespace: default  # Change if you want it in another namespace
type: Opaque
data:
  hf_api_token: "aGZfWEpObkZtbWZRYkVOTWFXbXFDanlpa2pKQnRSQ0VUTUxqeAo="
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adk-ray-agent-sa
  namespace: default
---
apiVersion: ray.io/v1
kind: RayService
metadata:
  name: llama-1p1b
spec:
  serveConfigV2: |
    applications:
      - name: llm
        route_prefix: terraform.inference.ray.serve-chat-completion
        import_path: serve-chat-completion.model
        runtime_env:
          working_dir: "https://github.com/damontfgz/chai-chatbot/archive/refs/heads/main.zip"
          env_vars:
            MODEL_ID: "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T"
            TENSOR_PARALLELISM: "1"
            MAX_MODEL_LEN: "4096"
            CHAT_TEMPLATE_PATH: "/templates/tool_chat_template_tinyllama_json.jinja"
        deployments:
          - name: VLLMDeployment
            num_replicas: 1
            ray_actor_options:
              num_cpus: 1
              num_gpus: 1
  rayClusterConfig:
    rayVersion: '2.37.0'
    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"
      template:
        metadata:
          labels:
            ai.gke.io: rayserve
        spec:
          serviceAccount: adk-ray-agent-sa
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 8Gi
            - name: chat-templates
              configMap:
                name: llama-chat-templates
          containers:
            - name: ray-head
              image: us-central1-docker.pkg.dev/gcp-home-dtian01/chatapp-docker-repo/llama-ray
              resources:
                limits:
                  cpu: "1"
                  memory: "10Gi"
                  ephemeral-storage: "20Gi"
                requests:
                  cpu: "1"
                  memory: "5Gi"
                  ephemeral-storage: "20Gi"
              ports:
                  # Ray Global Control Store
                  # Handles cluster metadata management, actor discovery, other control plane operations
                  # All Ray workers and drivers connect to this port
                - containerPort: 6379
                  name: gcs-server
                  # Ray Dashboard
                - containerPort: 8265
                  name: dashboard
                  # Ray Client server
                  # Enable remote connections to the Ray cluster. External clients can connect using: ray.init(address="ray://<host>:10001")
                - containerPort: 10001
                  name: client
                  # Ray Serve
                  # HTTP server for model server and inference requets
                - containerPort: 8000
                  name: serve
              env:
                - name: HUGGING_FACE_HUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: hf-secret
                      key: hf_api_token
                - name: PYTHONPATH
                  value: "/app:${PYTHONPATH}"
              volumeMounts:
              - mountPath: /dev/shm
                name: dshm
              - mountPath: /templates
                name: chat-templates
                readOnly: true
    workerGroupSpecs:
      - replicas: 1
        minReplicas: 1  # Ensure at least one worker
        maxReplicas: 1
        groupName: gpu-group
        rayStartParams: {}
        template:
          metadata:
            labels:
              ai.gke.io: rayserve
          spec:
            nodeSelector:
              cloud.google.com/gke-accelerator: nvidia-tesla-t4
            tolerations:
              - key: "nvidia.com/gpu"
                operator: "Exists"
                effect: "NoSchedule"
            serviceAccount: adk-ray-agent-sa
            volumes:
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 8Gi
            - name: chat-templates
              configMap:
                name: llama-chat-templates
            containers:
              - name: llm
                image: us-central1-docker.pkg.dev/gcp-home-dtian01/chatapp-docker-repo/llama-ray
                env:
                  - name: HUGGING_FACE_HUB_TOKEN
                    valueFrom:
                      secretKeyRef:
                        name: hf-secret
                        key: hf_api_token
                  - name: PYTHONPATH
                    value: "/app:${PYTHONPATH}"
                resources:
                  limits:
                    cpu: "1"
                    memory: "8Gi"
                    ephemeral-storage: "30Gi"
                    nvidia.com/gpu: "1"
                  requests:
                    cpu: "1"
                    memory: "8Gi"
                    ephemeral-storage: "30Gi"
                    # nvidia.com/gpu: "1"
                volumeMounts:
                - mountPath: /dev/shm
                  name: dshm
                - mountPath: /templates
                  name: chat-templates
                  readOnly: true
                # readinessProbe:
                #   exec:
                #     command:
                #       - bash
                #       - -c
                #       - wget -T 5 -q -O- http://localhost:52365/api/local_raylet_healthz | grep success
                #   initialDelaySeconds: 300
                #   periodSeconds: 30
                #   timeoutSeconds: 90
                #   failureThreshold: 15
                # livenessProbe:
                #   exec:
                #     command:
                #       - bash
                #       - -c
                #       - wget -T 5 -q -O- http://localhost:52365/api/local_raylet_healthz | grep success
                #   initialDelaySeconds: 60
                #   periodSeconds: 30
                #   timeoutSeconds: 10
                #   failureThreshold: 10
---
# See: https://github.com/vllm-project/vllm/blob/main/examples/tool_chat_template_llama3.1_json.jinja
apiVersion: v1
kind: ConfigMap
metadata:
  name: llama-chat-templates
data:
  tool_chat_template_tinyllama_json.jinja: |
    {%- for message in messages %}
      {%- if message['role'] == 'system' %}
          {{- '<|im_start|>system\n' + message['content'] + '<|im_end|>\n' }}
      {%- elif message['role'] == 'user' %}
          {{- '<|im_start|>user\n' + message['content'] + '<|im_end|>\n' }}
      {%- elif message['role'] == 'assistant' %}
          {{- '<|im_start|>assistant\n' + message['content'] + '<|im_end|>\n' }}
      {%- endif %}
    {%- endfor %}
    {{- '<|im_start|>assistant\n' }}